"""
Generated API Client for GitHubAPIClient
Auto-generated by reverse_api4
"""

import requests
import json
from typing import Any, Dict, Optional


class GitHubAPIClient:
    """API Client"""
    def __init__(self, base_url: str = ""):
        self.base_url = base_url.rstrip("/")
        self.headers = {}

    def get_users(self, username, **kwargs):
        """GET /users/{username}"""
        headers = {}
        url = f'/users/{}'
        response = requests.get(
            url,
            headers=headers,
        )
        response.raise_for_status()
        return response.json()
