"""
代码生成模块
根据分析结果生成 Python API 客户端代码和文档
"""

import json
import re
from typing import List, Optional, Dict, Any

from .models import AnalysisResult, APIEndpoint, AuthInfo


def _sanitize_name(name: str) -> str:
    """将字符串转换为合法的 Python 函数名"""
    # 替换特殊字符为下划线
    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    # 替换多个下划线为一个
    name = re.sub(r"_+", "_", name)
    # 去掉开头结尾的下划线
    name = name.strip("_")
    # 如果以数字开头，加前缀
    if name and name[0].isdigit():
        name = "api_" + name
    return name or "unknown"


def _extract_path_params(url: str) -> tuple[str, List[str]]:
    """提取 URL 中的路径参数，返回 (normalized_url, param_names)"""
    params = re.findall(r"\{([^}]+)\}", url)
    normalized = re.sub(r"\{[^}]+\}", "{}", url)
    return normalized, params


def _guess_function_name(endpoint: APIEndpoint) -> str:
    """根据 URL 和方法猜测函数名"""
    # 移除基础 URL，只保留路径
    url = endpoint.url
    # 移除协议和域名
    url = re.sub(r"https?://[^/]+", "", url)
    # 移除路径参数（如 {id}）
    url = re.sub(r"\{[^}]+\}", "", url)
    # 按 / 分割
    parts = [p for p in url.split("/") if p]
    # 过滤掉常见前缀
    parts = [p for p in parts if p.lower() not in ("api", "v1", "v2", "v3")]
    # 使用最后一个有意义的路径部分
    if not parts:
        return "api_call"
    name = parts[-1]
    # 添加方法前缀
    method_prefix = {
        "GET": "get",
        "POST": "create",
        "PUT": "update",
        "DELETE": "delete",
        "PATCH": "patch",
    }.get(endpoint.method, "call")
    return _sanitize_name(f"{method_prefix}_{name}")


def _generate_method_code(endpoint: APIEndpoint, func_name: str) -> str:
    """为一个端点生成方法代码"""
    lines = []
    ep = endpoint
    url, path_params = _extract_path_params(ep.url)

    # 函数签名
    params = ["self"]
    if path_params:
        params.extend(path_params)
    params.append("**kwargs")
    lines.append(f"    def {func_name}({', '.join(params)}):")
    lines.append(f'        """{ep.method} {ep.url}"""')

    # 构建请求参数
    if ep.headers:
        # 添加自定义头
        lines.append("        headers = {")
        for k, v in list(ep.headers.items())[:5]:  # 只取前5个
            if k.lower() not in ("host", "content-length", "connection"):
                lines.append(f"            '{k}': '{v[:50]}',")
        lines.append("        }")
    else:
        lines.append("        headers = {}")

    # URL（如果有路径参数）
    if path_params:
        lines.append(f"        url = f'{url}'")
    else:
        lines.append(f"        url = '{ep.url}'")

    # 请求体
    body_param = ""
    if ep.method in ("POST", "PUT", "PATCH") and ep.body:
        lines.append("        json_data = kwargs.get('json', None)")
        body_param = ", json=json_data"

    # 查询参数
    query_param = ""
    if ep.params:
        lines.append("        params = kwargs.get('params', {})")
        query_param = ", params=params"

    # 发送请求
    lines.append(f"        response = requests.{ep.method.lower()}(")
    lines.append("            url,")
    lines.append("            headers=headers" + query_param + body_param + ",")
    lines.append("        )")
    lines.append("        response.raise_for_status()")
    lines.append("        return response.json()")
    lines.append("")

    return "\n".join(lines)


def _generate_auth_setup(auth_info: Optional[AuthInfo]) -> str:
    """生成认证设置代码"""
    if not auth_info:
        return ""

    lines = ["    def __init__(self, base_url: str = ''):"]
    lines.append("        self.base_url = base_url.rstrip('/')")

    if auth_info.type == "bearer":
        lines.append("        self.token = ''  # 设置你的 Bearer Token")
        # 生成代码：self.headers = {'Authorization': f'Bearer {self.token}'}
        lines.append("        self.headers = {'Authorization': f'Bearer {self.token}'}")
    elif auth_info.type == "api-key":
        lines.append("        self.api_key = ''  # 设置你的 API Key")
        if auth_info.location == "header":
            key = auth_info.key_name
            # 生成代码：self.headers = {'X-API-Key': self.api_key}
            lines.append("        self.headers = {'" + key + "': self.api_key}")
        else:
            lines.append("        self.headers = {}")
    elif auth_info.type == "basic":
        lines.append("        self.username = ''  # 设置用户名")
        lines.append("        self.password = ''  # 设置密码")
        lines.append("        self.headers = {}  # 使用 HTTPBasicAuth，调用时传 auth=(user, pass)")
    else:
        lines.append("        self.headers = {}")

    lines.append("")
    return "\n".join(lines)


def generate_python_client(result: AnalysisResult, class_name: str = "APIClient") -> str:
    """
    生成 Python requests 风格的 API 客户端

    Args:
        result: 分析结果
        class_name: 生成的类名

    Returns:
        Python 代码字符串
    """
    lines = []
    lines.append('"""')
    lines.append(f"Generated API Client for {class_name}")
    lines.append("Auto-generated by reverse_api4")
    lines.append('"""')
    lines.append("")
    lines.append("import requests")
    lines.append("import json")
    lines.append("from typing import Any, Dict, Optional")
    lines.append("")
    lines.append("")

    # 类定义
    lines.append(f"class {class_name}:")
    lines.append('    """API Client"""')

    # __init__ 方法（认证）
    if result.auth_info:
        lines.append(_generate_auth_setup(result.auth_info).replace("    def __init__", "    def __init__", 1))
    else:
        lines.append('    def __init__(self, base_url: str = ""):')
        lines.append('        self.base_url = base_url.rstrip("/")')
        lines.append("        self.headers = {}")
        lines.append("")

    # 为每个端点生成方法
    if result.endpoints:
        for ep in result.endpoints:
            func_name = _guess_function_name(ep)
            method_code = _generate_method_code(ep, func_name)
            lines.append(method_code)
    else:
        lines.append("    # 未识别到端点，请手动添加方法")
        lines.append("    pass")
        lines.append("")

    return "\n".join(lines)


def generate_api_doc(result: AnalysisResult, title: str = "API Documentation") -> str:
    """
    生成 Markdown API 文档

    Args:
        result: 分析结果
        title: 文档标题

    Returns:
        Markdown 文档字符串
    """
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("Auto-generated by reverse_api4")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 认证信息
    if result.auth_info:
        lines.append("## Authentication")
        lines.append("")
        lines.append(f"**Type:** {result.auth_info.type}")
        if result.auth_info.key_name:
            lines.append(f"**Key:** `{result.auth_info.key_name}`")
        if result.auth_info.location:
            lines.append(f"**Location:** {result.auth_info.location}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # 端点列表
    lines.append("## Endpoints")
    lines.append("")

    if not result.endpoints:
        lines.append("No endpoints identified.")
        return "\n".join(lines)

    for i, ep in enumerate(result.endpoints, 1):
        lines.append(f"### {i}. {ep.method} {ep.url}")
        lines.append("")

        if ep.params:
            lines.append("**Query Parameters:**")
            for k, v in ep.params.items():
                lines.append(f"- `{k}`: {v}")
            lines.append("")

        if ep.body:
            lines.append("**Request Body:**")
            lines.append("```json")
            try:
                body_json = json.loads(ep.body) if isinstance(ep.body, str) else ep.body
                lines.append(json.dumps(body_json, indent=2))
            except:
                lines.append(str(ep.body)[:200])
            lines.append("```")
            lines.append("")

        if ep.response_body:
            lines.append("**Response Example:**")
            lines.append("```json")
            try:
                resp_json = json.loads(ep.response_body) if isinstance(ep.response_body, str) else ep.response_body
                lines.append(json.dumps(resp_json, indent=2)[:500])
            except:
                lines.append(str(ep.response_body)[:200])
            lines.append("```")
            lines.append("")

        lines.append("---")
        lines.append("")

    # 总结
    if result.summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(result.summary)
        lines.append("")

    return "\n".join(lines)


def generate_openapi_spec(result: AnalysisResult, title: str = "API") -> str:
    """
    生成 OpenAPI 3.0 规范

    Args:
        result: 分析结果
        title: API 标题

    Returns:
        OpenAPI spec JSON 字符串
    """
    spec = {
        "openapi": "3.0.0",
        "info": {"title": title, "version": "1.0.0", "description": "Auto-generated by reverse_api4"},
        "servers": [],
        "paths": {},
    }

    # 收集基础 URL
    base_urls = set()
    for ep in result.endpoints:
        match = re.match(r"https?://[^/]+", ep.url)
        if match:
            base_urls.add(match.group())

    for base_url in base_urls:
        spec["servers"].append({"url": base_url})

    # 处理端点
    for ep in result.endpoints:
        url, path_params = _extract_path_params(ep.url)
        # 移除基础 URL
        path = re.sub(r"https?://[^/]+", "", url)

        if path not in spec["paths"]:
            spec["paths"][path] = {}

        method_lower = ep.method.lower()
        spec["paths"][path][method_lower] = {"summary": f"{ep.method} {path}", "parameters": []}

        # 路径参数
        for param in path_params:
            spec["paths"][path][method_lower]["parameters"].append({"name": param, "in": "path", "required": True, "schema": {"type": "string"}})

        # 查询参数
        if ep.params:
            for k, v in ep.params.items():
                spec["paths"][path][method_lower]["parameters"].append({"name": k, "in": "query", "schema": {"type": "string"}})

        # 请求体
        if ep.method in ("POST", "PUT", "PATCH") and ep.body:
            spec["paths"][path][method_lower]["requestBody"] = {"content": {"application/json": {"schema": {"type": "object"}, "example": ep.body}}}

        # 响应
        spec["paths"][path][method_lower]["responses"] = {
            "200": {"description": "Successful response", "content": {"application/json": {"example": ep.response_body if ep.response_body else {}}}}
        }

    return json.dumps(spec, indent=2, ensure_ascii=False)


def generate_all(result: AnalysisResult, class_name: str = "APIClient", title: str = "API") -> dict:
    """
    生成所有输出

    Returns:
        dict with keys: client_code, api_doc, openapi_spec
    """
    return {
        "client_code": generate_python_client(result, class_name),
        "api_doc": generate_api_doc(result, title),
        "openapi_spec": generate_openapi_spec(result, title),
    }
